### ISSUE TITLE
股票代码和股票名称

### ISSUE THREAD

**Issue by xffforever** [ericyan/tdx#1]
日线和五分钟数据没问题 知道从哪个文件获取股票代码和股票名称的映射吗

**Comment by ericyan** [comment]
这个库将专注于解析报价数据。如果需要获取证券代码及简称，建议直接从交易所获取：
- 上交所：http://www.sse.com.cn/js/common/ssesuggestdata.js
- 深交所：http://www.szse.cn/szseWeb/ShowReport.szse?SHOWTYPE=EXCEL&CATALOGID=1110&tab1PAGENUM=1&ENCODE=1&TABKEY=tab1
