### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AllanChain** [ericyan/tdx#3]
https://github.com/ericyan/tdx/blob/7a9cf79adebe3c82be6fa41bd87f60ef14e32561/tdx.go#L54-L56
https://github.com/ericyan/tdx/blob/7a9cf79adebe3c82be6fa41bd87f60ef14e32561/tdx.go#L97-L99

`RawLow` should be `RawClose`

**Comment by ericyan** [comment]
Nice catch. Could you prepare a MR for this?
